In [2]:
import numpy as np

In [2]:
#Задание 1

In [3]:
a = np.arange(12,24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [4]:
#Задание 2

In [14]:
b1 = a.reshape(3,4)
print(b1)
b2 = a.reshape(2,6)
print(b2)
b3 = a.reshape(4,3)
print(b3)
b4 = a.reshape(6,2)
print(b4)
b5 = a.reshape(12,1)
print(b5)


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [7]:
#Задание 3

In [16]:
c1 = a.reshape(3,-1)
print(c1)
c2 = a.reshape(2,-1)
print(c2)
c3 = a.reshape(4,-1)
print(c3)
c4 = a.reshape(-1,2)
print(c4)
c5 = a.reshape(-1,12)
print(c5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


In [17]:
#Задание 4

In [20]:
#Проверим размерность такого массива при помощи атрибута ndim 
b5.ndim

2

In [21]:
#Полуечнный результат показывает, что размерность такого массива равна 2 и его нельзя считать одномерным

In [22]:
#Задание 5

In [3]:
b = np.random.randn(3,4)
print(b)

[[ 0.21493001 -1.20732916 -1.37389066 -0.88536272]
 [ 1.7978839   1.65829446 -1.37015155  0.49691105]
 [-0.51216969 -0.62311611  1.32090361  1.35607138]]


In [4]:
b.size

12

In [5]:
c = b.flatten()
print(c)

[ 0.21493001 -1.20732916 -1.37389066 -0.88536272  1.7978839   1.65829446
 -1.37015155  0.49691105 -0.51216969 -0.62311611  1.32090361  1.35607138]


In [6]:
c.ndim

1

In [7]:
c.size

12

In [27]:
#Задание 6

In [28]:
a = np.arange(20,0,-2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [29]:
#Задание 7

In [30]:
bb = np.arange(20,1,-2)
b = bb.reshape(1,10)
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


In [31]:
print(a.ndim)
print(b.ndim)


1
2


In [32]:
#Таким образом, разница массивов a и b в их размерности. Массив a является одномерным, в то время как массив b - двумерным

In [33]:
#Задание 8

In [38]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

In [39]:
v = np.vstack((a, b))

print(v)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
v.size

10

In [41]:
#Задание 9

In [8]:
a = np.arange(0,12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
A=a.reshape(4,3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
At = np.transpose(A)
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [11]:
B = A.dot(At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [12]:
B.ndim

2

In [13]:
#Найдем определитель матрицы B
d = np.linalg.det(B)
print(d)

0.0


In [49]:
#Определитель равен 0, поэтому обратную матрицу посчитать не получится

In [50]:
#Задание 10

In [14]:
np.random.seed(42)

In [52]:
#Задание 11

In [15]:
c = np.random.randint(0, 16, 16)

print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


In [56]:
#Задание 12

In [16]:
C = c.reshape(4,4)
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [17]:
D = B + 10*C
print(D)

[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [18]:
d = np.linalg.det(D)
print(d)

-28511999.999999944


In [19]:
r = np.linalg.matrix_rank(D)

print(r)

4


In [20]:
D_inv = np.linalg.inv(D)

print(D_inv)

[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


In [65]:
#Задание 13

In [21]:
a, b = 0, 1
D_inv = (D_inv > a) * b
print(D_inv)

[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]


In [22]:
print(B)
print(C)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [23]:
E = np.where(D_inv == 1, B, C)

print(E)

[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
