In [1]:
#Задание 1
import numpy as np

In [3]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11],
              [3,10],
              [1,7]])
print("Форма a: {}".format(a.shape))

Форма a: (5, 2)


In [5]:
mean_a = a.mean(axis=0)
print("Средние значения по признаку: {}".format(mean_a))

Средние значения по признаку: [2.  8.4]


In [6]:
#Задание 2

In [9]:
a_centered = a - mean_a
print(a_centered)
print("Форма a_centered: {}".format(a_centered.shape))

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]
Форма a_centered: (5, 2)


In [10]:
#Задание 3

In [20]:
a_centered_sp = a_centered[:,0].dot(a_centered[:,1])
print("Скалярное произведение столбцов: {}".format(a_centered_sp))
N = a.shape[0]
a_centered_sp = a_centered_sp/(N-1)
print("Ковариация признаков: {}".format(a_centered_sp))

Скалярное произведение столбцов: 8.0
Ковариация признаков: 2.0


In [21]:
#Задание 4

In [26]:
a_t = a.T
print(a_t)
at_cov2 = np.cov(a_t)
cov2 = at_cov2[0,1]
print("Ковариация признаков: {}".format(cov2))

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
Ковариация признаков: 2.0
